name: Unity Test

on: [push, pull_request]

permissions: write-all

jobs:
  build:
    name: Unity Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2021.3.42f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
